# Generated by Django 5.0 on 2023-12-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_by', to='users_app.profiles'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_profiles',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='users_app.profiles'),
        ),
    ]
